# Generated by Django 5.2.4 on 2025-08-06 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carimage',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='carimage',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
